### ISSUE TITLE
Problem with signals.swift for upgraded swift version 4.2

### ISSUE THREAD

**Issue by arkeo01** [IBM-Swift/BlueSignals#13]
There is an error in the file BlueSignals/Sources/Signals/**Signals.swift**...
The Error is as follows:
111:36: error: converting non-escaping value to 'T' may allow it to escape
                        sigAction.__sigaction_handler = unsafeBitCast(action, to: sigaction.__Unnamed_union___sigaction_handler.self)
                                                        ^
error: terminated(1)

**Comment by arkeo01** [comment]
import PackageDescription

var deps: [Package.Dependency] = [
	.package(url: "https://github.com/pixelspark/sqlite.git", from: Version("3.0.0")),
	.package(url: "https://github.com/pixelspark/postgres-wire-server.git", from: Version("1.0.0")),
	.package(url: "https://github.com/IBM-Swift/Kitura.git", from: Version("2.0.0")),    
	.package(url: "https://github.com/jatoben/CommandLine.git", from: Version("3.0.0-pre1")),
	.package(url: "https://github.com/pixelspark/swift-parser-generator.git", from: Version("2.0.2")),
	.package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: Version("1.7.1")),
	.package(url: "https://github.com/vzsg/ed25519.git", from: Version("0.2.0")),
	.package(url: "https://github.com/pixelspark/base58.git", from: Version("1.0.0")),
	.package(url: "https://github.com/Bouke/NetService.git", from: Version("0.0.0")),
	.package(url: "https://github.com/IBM-Swift/Kitura-WebSocket", from: Version("1.0.0")),
]

Following are the dependencies used....

**Comment by arkeo01** [comment]
`import PackageDescription

var deps: [Package.Dependency] = [
	.package(url: "https://github.com/pixelspark/sqlite.git", from: Version("3.0.0")),
	.package(url: "https://github.com/pixelspark/postgres-wire-server.git", from: Version("1.0.0")),
	.package(url: "https://github.com/IBM-Swift/Kitura.git", from: Version("2.0.0")),   
	.package(url: "https://github.com/jatoben/CommandLine.git", from: Version("3.0.0-pre1")),
	.package(url: "https://github.com/pixelspark/swift-parser-generator.git", from: Version("2.0.2")),
	.package(url: "https://github.com/IBM-Swift/HeliumLogger.git", from: Version("1.7.1")),
	.package(url: "https://github.com/vzsg/ed25519.git", from: Version("0.2.0")),
	.package(url: "https://github.com/pixelspark/base58.git", from: Version("1.0.0")),
	.package(url: "https://github.com/Bouke/NetService.git", from: Version("0.0.0")),
	.package(url: "https://github.com/IBM-Swift/Kitura-WebSocket", from: Version("1.0.0")),
]`

Following are the dependencies used...

**Comment by billabt** [comment]
This looks like Kitura may be pulling the wrong version of _BlueSignals_ or have a dependency issue.  Please open an issue against **Kitura**.  The current version of _BlueSignals_ appears to be working fine here when I just tested it using the for 4.2 compiler.

**Comment by ianpartridge** [comment]
Closing as we're tracking this in #1352 on Kitura.
