### ISSUE TITLE
Cannot capture context in callback closure

### ISSUE THREAD

**Issue by potmo** [IBM-Swift/BlueSignals#28]
This code
```swift
let a = {
   print("got here")
}

Signals.trap(signal: .user(Int(SIGWINCH))) { _ in
   a() 
}
```
generates this error message:
`A C function pointer cannot be formed from a closure that captures context`

I hoped that Signals would workaround this issue for me since I got the same message when calling the native signal trapping code i.e.
```swift
signal(SIGWINCH, {_ in
   a()
})
```

maybe it would be nice if this was mentioned in the readme or some documentation on how to get around it.

**Comment by potmo** [comment]
btw I'm using XCode `Version 13.4.1 (13F100)` 
and 
```
$ swift --version
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: x86_64-apple-macosx12.0
```

I cant really see how the example in the documentation would work since it captures `server` into the closure

```swift 
let server: SomeServer = ...
Signals.trap(signal: .int) { signal in
	server.shutdownServer()
}
server.run()
```

**Comment by potmo** [comment]
I just saw that this is a duplicate if #4 
Sorry I'll close

**Comment by dannys42** [comment]
Interesting.  I might have some ideas on how to improve this.  It might be sometime before I'm able to work on it though.
