### ISSUE TITLE
Closures not working?

### ISSUE THREAD

**Issue by oderwat** [IBM-Swift/BlueSignals#4]
I wonder about the example code which looks to me like it is using a closure which captured context. In my similar code I get the following error:

> error: a C function pointer cannot be formed from a closure that captures context

This makes it pretty hard to do anything of value inside the signal handler.

I "hacked" it with a global variable for my code but I wonder if there is a better solution for this problem or if I did something totally wrong?

**Comment by billabt** [comment]
They appear to running fine here.  Can you show me some code that illustrates the problem?  Thanks.

**Comment by oderwat** [comment]
My guess why you can't reproduce what I mean is because your example runs with a global and there is no captured context for a closure:

```
import Signals

...

let server: SomeServer = ...

Signals.trap(signal: .int) { signal in

	server.shutdownServer()
}

server.run()
```

My usage looks more like this:

```
import Signals

func test() {

    let server: SomeServer = ...

    Signals.trap(signal: .int) { signal in
        server.shutdownServer()
    }

    server.run()
}
```

Here is my real world example which I tried with your implementation (while I know use "signal()" instead:

https://github.com/oderwat/BearNanny/blob/master/Sources/BearNanny/main.swift

I would like to avoid using the "globalTask" and instead use a closure capture.

Meanwhile I think there is no (halve way easy) solution for the problem as I could not find any way to hand some custom data to the signal handler.

**Comment by emrahgunduz** [comment]
This is a Swift limitation/problem than the package.
I simply passed the problem by using NotificationCenter. `main.swift` file contains:
```swift
func signalHandler (signal: Int32) {
  NotificationCenter.default.post(name: Notification.Name(rawValue: "signalRecevied"), object: signal)
}

Signals.trap(signals: [.hup, .int, .quit, .abrt, .kill, .alrm, .term, .pipe], action: signalHandler)
```
And in a class type file, this resides:
```swift
  private let notificationName = Notification.Name(rawValue: "signalRecevied")
  private var observer:NSObjectProtocol?

  public func startListeningNotifications () {
    let signalReceived: (Notification) -> Void = { notification in
      NotificationCenter.default.removeObserver(self.observer!)

      guard let signal = notification.object as? Int32 else {
        return
      }

      // ... more operations here...
    }

    self.observer = NotificationCenter.default.addObserver(forName: self.notificationName, object: nil, queue: OperationQueue.main, using: signalReceived)
  }
```
I'm working on an Ubuntu 16.04 machine, and this works as expected.
