### ISSUE TITLE
Unable to capture signals in app delegate closure.

### ISSUE THREAD

**Issue by cvamsi2** [IBM-Swift/BlueSignals#7]
I tried to crash my iOS 11 app by accessing out of bounds elements from an Array. 

In the app delegate's **did finish launching with options**, I declared like the below
```
Signals.trap(signals: [.abrt, .alrm, .hup, .int, .kill, .pipe, .quit, .term]) { (signal) in
            print("Received signal \(signal)")
}
```
However, I am still not able to catch swift runtime exceptions. Pls guide.

**Comment by billabt** [comment]
This signal handler is not designed to (nor can it in any way, see the link below) catch _Swift Runtime exceptions_.  It's only able to catch _operating system signals_.  Things like out of bounds errors are generated by the Swift runtime not the operating system and therefore cannot be caught.  Take a look at this [link](https://stackoverflow.com/questions/38737880/uncaught-error-exception-handling-in-swift) for more information and the rationale for _why_ you can't catch these runtime errors.
